{{- if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kserve-setup.fullname" . }}-proxy
  labels:
    {{- include "kserve-setup.proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "kserve-setup.proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kserve-setup.proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kserve-setup.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.proxy.podSecurityContext | nindent 8 }}
      containers:
        - name: kserve-proxy
          securityContext:
            {{- toYaml .Values.proxy.securityContext | nindent 12 }}
          image: "{{ include "kserve-setup.imageRepository" (dict "global" .Values.global "repository" .Values.proxy.image.repository) }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ include "kserve-setup.imagePullPolicy" .Values.proxy.image }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.service.port }}
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          env:
            {{- toYaml .Values.proxy.env | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- if .Values.proxy.healthChecks.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.proxy.healthChecks.liveness.path | default "/health" }}
              port: {{ .Values.proxy.healthChecks.liveness.port | default "http" }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.proxy.healthChecks.readiness.path | default "/ready" }}
              port: {{ .Values.proxy.healthChecks.readiness.port | default "http" }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          {{- end }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kserve-setup.fullname" . }}-proxy
  labels:
    {{- include "kserve-setup.proxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "kserve-setup.proxy.selectorLabels" . | nindent 4 }}
{{- end }}


