controller:
  image:
    repository: reg.mini.dev/ingress-nginx-controller
    tag: latest
    digest: null
    runAsUser: 1000
    runAsGroup: 1000
  imagePullSecrets:
  - name: minimus-pull-secret
  admissionWebhooks:
    createSecretJob:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
    patch:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
