# ConfigMap for Alertmanager configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: default
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'default-receiver'
    
    receivers:
    - name: 'default-receiver'
      webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

---
# Service for Alertmanager
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: default
spec:
  selector:
    app: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: 9093
  type: ClusterIP

---
# Deployment with Alertmanager and configmap-reload sidecar
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      # Main Alertmanager container
      - name: alertmanager
        image: reg.mini.dev/prometheus-alertmanager:latest
        ports:
        - containerPort: 9093
        args:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
          - '--web.external-url=http://localhost:9093'
          - '--web.route-prefix=/'
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: storage-volume
          mountPath: /alertmanager
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      
      # ConfigMap reload sidecar container
      - name: configmap-reload
        image: reg.mini.dev/configmap-reload:latest
        args:
          - '--volume-dir=/etc/alertmanager'
          - '--webhook-url=http://localhost:9093/-/reload'
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: storage-volume
        emptyDir: {}

---
# Optional: NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30093
