apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: frontend
        image: reg.mini.dev/busybox:latest-dev
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Calling backend...'; wget -qO- http://backend/; sleep 10; done"]
      imagePullSecrets:
      - name: my-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: istio-system
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
