apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-for-fluent-bit
  namespace: kube-system
imagePullSecrets:
- name: minimus-registry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-for-fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On

    [INPUT]
        Name              tail
        Path              /var/log/dmesg
        Tag               node.dmesg
        Refresh_Interval  5
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Read_from_Head    true

    [INPUT]
        Name              tail
        Path              /var/log/secure
        Tag               node.secure
        Refresh_Interval  5
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Read_from_Head    true

    [INPUT]
        Name              tail
        Path              /var/log/messages
        Tag               node.messages
        Refresh_Interval  5
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Read_from_Head    true

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name        cloudwatch_logs
        Match       kube.*
        region      eu-north-1
        log_group_name  /aws/containerinsights/kube-system/application
        log_stream_prefix  containers-
        auto_create_group true

    [OUTPUT]
        Name        cloudwatch_logs
        Match       node.*
        region      eu-north-1
        log_group_name  /aws/containerinsights/kube-system/node
        log_stream_prefix  node-
        auto_create_group true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-for-fluent-bit
  namespace: kube-system
  labels:
    app: aws-for-fluent-bit
spec:
  selector:
    matchLabels:
      app: aws-for-fluent-bit
  template:
    metadata:
      labels:
        app: aws-for-fluent-bit
    spec:
      serviceAccountName: aws-for-fluent-bit
      imagePullSecrets:
      - name: minimus-registry
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: aws-for-fluent-bit
        # Replace default image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        image: reg.mini.dev/aws-for-fluent-bit:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SESSION_TOKEN
              optional: true
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_DEFAULT_REGION
              optional: true
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 100m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - DAC_OVERRIDE
            - CHOWN
            - FOWNER
            - SETUID
            - SETGID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: config-volume
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: fluent-bit-state
          mountPath: /var/lib/fluent-bit
        - name: fluent-bit-buffers
          mountPath: /tmp/fluent-bit-buffers
      volumes:
      - name: config-volume
        configMap:
          name: aws-for-fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: tmp
        emptyDir: {}
      - name: fluent-bit-state
        emptyDir: {}
      - name: fluent-bit-buffers
        emptyDir: {}
      tolerations:
      - operator: Exists
        effect: NoSchedule